### ISSUE TITLE
Local installation does not works as demo

### ISSUE THREAD

**Issue by almasou** [sdaps/sdaps_web#12]
Hello, I have installed sdaps_web following the README.md instructions and it installs without errors.
I can go to localhost:8080 and log in with admin and my pass, I can create a new survey but when editing the survey I can't see the previsualization at right side as it can be seen in https://demo.sdaps.org, it renders nothing.
If I try to preview pdf in Step 1 it shows the following error:
```
Page not found (404)
Request Method: 	GET
Request URL: 	http://localhost:8080/surveys/1/questionnaire.pdf
Raised by: 	sdaps_ctl.views.questionnaire_download
```
The same occurs when I try to download .tex

If I click on Setup survey in Step 2, it reload the page but the survey is not initialized, so I can't continue with step 3.

Is the code installed in https://demo.sdaps.org exactly the same version we get with 

> git clone https://github.com/sdaps/sdaps_web

 command?

Is there any log I can check to go in depth?

The only step maybe I don't follow in installation was:
```
Then open another terminal window, repeat source .venv/bin/activate in the same directory and the export of the PYTHONPATH above in the new terminal and run:

python -m celery -A sdaps_web worker -Q background,default -E
```
I only did:
```
Then open another terminal window, repeat source .venv/bin/activate in the same directory in the new terminal and run:
python -m celery -A sdaps_web worker -Q background,default -E
```
because I don't understand what I must do with PYTHONPATH. Can this be the problem?

I have tried multiple installs on Lubuntu 16.04.5 and Lubuntu 18.04.1.

I would use sdaps_web locally as the demo, is this possible?

Thanks for this great software.

**Comment by pauloerweber** [comment]
Having the exact same issue.

**Comment by benzea** [comment]
Can you provide more information?

I would expect some output from the celery process (at least pdflatex compile runs). Also, you could check in the project directory and see which files were created for the project.

The most likely explanation could be a LaTeX compile error. There may be a `questionnaire.log` file or so in the project directory that will give you more information about the failure.

**Comment by benzea** [comment]
Right "The same occurs when I try to download .tex" sounds more like the project directory is not created. You do realise that the example uses /tmp/projects which is only useful for temporary testing. You will need to change the path to some permanent directory and make sure it is both created and the processes can write to it.

**Comment by almasou** [comment]
When I create a new survey in web, it creates a new folder in /tmp/projects and inside it there are the following files:
 code128.tex                                  translator-sdaps-dictionary-French.dict
 sdapsarray.sty                               translator-sdaps-dictionary-German.dict
 sdapsbase.sty                                translator-sdaps-dictionary-Italian.dict
 sdapsclassic.cls                            'translator-sdaps-dictionary-Norwegian Bokmål.dict'
 sdapslayout.sty                              translator-sdaps-dictionary-Polish.dict
 sdapspdf.sty                                 translator-sdaps-dictionary-Portuguese.dict
 sdapsreport.cls                              translator-sdaps-dictionary-Romanian.dict
 translator-sdaps-dictionary-Brazilian.dict   translator-sdaps-dictionary-Sinhala.dict
 translator-sdaps-dictionary-Dutch.dict       translator-sdaps-dictionary-Spanish.dict
 translator-sdaps-dictionary-English.dict     translator-sdaps-dictionary-Swedish.dict
 translator-sdaps-dictionary-Finnish.dict     translator-sdaps-dictionary-Ukrainian.dict

There is neither questionnaire.tex nor questionnaire.log as it must.

What more can I do?

**Comment by almasou** [comment]
The following is the output of the processes python runserver and celery since its launching until I create a new survey and try to download .tex from step 1 through the web:

(.venv) usu@Lubuntu18SDAPS:~/sdaps_web$ python manage.py runserver localhost:8080
Performing system checks...

```
System check identified no issues (0 silenced).
December 17, 2018 - 23:48:33
Django version 2.1.2, using settings 'sdaps_web.settings'
Starting development server at http://localhost:8080/
Quit the server with CONTROL-C.
[17/Dec/2018 23:49:00] "GET / HTTP/1.1" 302 0
[17/Dec/2018 23:49:00] "GET /surveys HTTP/1.1" 200 3671
[17/Dec/2018 23:49:02] "GET /surveys/create HTTP/1.1" 200 5172
[17/Dec/2018 23:49:14] "POST /surveys/create HTTP/1.1" 302 0
[17/Dec/2018 23:49:14] "GET /surveys HTTP/1.1" 200 3924
[17/Dec/2018 23:49:17] "GET /surveys/5 HTTP/1.1" 200 7772
Not Found: /surveys/5/questionnaire.tex
[17/Dec/2018 23:49:21] "GET /surveys/5/questionnaire.tex HTTP/1.1" 404 1753
[17/Dec/2018 23:49:27] "GET /surveys/5/edit HTTP/1.1" 200 22984
[17/Dec/2018 23:49:27] "GET /static/sdaps_ctl/css/angular-ui-tree.min.css HTTP/1.1" 304 0
[17/Dec/2018 23:49:27] "GET /static/sdaps_ctl/angular.min.js HTTP/1.1" 304 0
[17/Dec/2018 23:49:27] "GET /static/sdaps_ctl/angular-ui-tree.min.js HTTP/1.1" 304 0
[17/Dec/2018 23:49:27] "GET /static/sdaps_ctl/pdf.js HTTP/1.1" 304 0
[17/Dec/2018 23:49:27] "GET /static/sdaps_ctl/edit_questionnaire.js HTTP/1.1" 304 0
[17/Dec/2018 23:49:27] "GET /static/sdaps_ctl/pdf_preview.js HTTP/1.1" 304 0
[17/Dec/2018 23:49:28] "GET /surveys/5/edit/questionnaire HTTP/1.1" 200 2
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:28] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
[17/Dec/2018 23:49:33] "POST /surveys/5/edit/questionnaire HTTP/1.1" 200 36
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:34] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:34] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:35] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:35] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:36] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:36] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:37] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:37] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:38] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
[17/Dec/2018 23:49:38] "GET /surveys/5 HTTP/1.1" 200 7772
Not Found: /surveys/5/questionnaire.pdf
[17/Dec/2018 23:49:38] "GET /surveys/5/questionnaire.pdf HTTP/1.1" 404 1749
Not Found: /surveys/5/questionnaire.tex
[17/Dec/2018 23:49:42] "GET /surveys/5/questionnaire.tex HTTP/1.1" 404 1753
```



```
(.venv) usu@Lubuntu18SDAPS:~/sdaps_web$ python -m celery -A sdaps_web worker -Q background,default -E
 
 -------------- celery@Lubuntu18SDAPS v4.2.1 (windowlicker)
---- **** ----- 
--- * ***  * -- Linux-4.15.0-42-generic-x86_64-with-Ubuntu-18.04-bionic 2018-12-17 23:48:46
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         sdaps_web:0x7fea94b78b38
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: ON
--- ***** ----- 
 -------------- [queues]
                .> background       exchange=background(direct) key=background
                .> default          exchange=default(direct) key=default

[2018-12-17 23:48:47,453: WARNING/MainProcess] /home/usu/sdaps_web/.venv/lib/python3.6/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
```

I hope this will be useful, otherwise tell me what you need.
Thanks.

**Comment by benzea** [comment]
The `questionnaire.tex` file will be created when you open the editor. At that point you should also get a `questionnaire.log`, `questionnaire.pdf` and some more files.

If compilation fails, then `questionnaire.pdf` will be missing, however, you should still have the log file. See also issue #9.

**Comment by benzea** [comment]
Oh, wait. It looks like the celery worker never processes any tasks. The survey directory is created directly from the web service (which seems like a bug), so you get that, but everything else fails.

Are you sure that your rabbitmq service is up and running?

**Comment by pauloerweber** [comment]
In my case rabbitmq-server is up. 
<pre>
~$ service rabbitmq-server status
● rabbitmq-server.service - RabbitMQ Messaging Server
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-12-18 09:37:24 -02; 7min ago
  Process: 1637 ExecStop=/usr/sbin/rabbitmqctl stop (code=exited, status=0/SUCCESS)
  Process: 2392 ExecStartPost=/usr/lib/rabbitmq/bin/rabbitmq-server-wait (code=exited, status=0/SUCCESS)
 Main PID: 2391 (rabbitmq-server)
    Tasks: 88 (limit: 4680)
   Memory: 70.9M
   CGroup: /system.slice/rabbitmq-server.service
           ├─2391 /bin/sh /usr/sbin/rabbitmq-server
           ├─2414 /bin/sh /usr/lib/rabbitmq/bin/rabbitmq-server
           ├─2735 /usr/lib/erlang/erts-9.3.3.3/bin/epmd -daemon
           ├─2894 /usr/lib/erlang/erts-9.3.3.3/bin/beam.smp -W w -A 64 -P 1048576 -t 5000000 -stbt db -zdbbl 32000 -K true -B i -- -root /usr/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /us
           ├─3022 erl_child_setup 65536
           ├─3085 inet_gethost 4
           └─3086 inet_gethost 4

dez 18 09:37:20 weber-VirtualBox systemd[1]: Starting RabbitMQ Messaging Server...
dez 18 09:37:21 weber-VirtualBox rabbitmq[2392]: Waiting for 'rabbit@weber-VirtualBox'
dez 18 09:37:21 weber-VirtualBox rabbitmq[2392]: pid is 2414
dez 18 09:37:24 weber-VirtualBox systemd[1]: Started RabbitMQ Messaging Server.
lines 1-21/21 (END)

</pre>

Still, no sign of the questionnarie.tex file.

**Comment by almasou** [comment]
> Are you sure that your rabbitmq service is up and running?

Yes, rabbitmq-server is up and running like pauloerweber's

What can I check?

**Comment by benzea** [comment]
To be honest, I have no idea right now …

**Comment by almasou** [comment]
Any progress on this issue?
Could you try to install sdaps_web in a virtual machine following your steps and check if they are enough or if some more steps are needed?

Thanks.

**Comment by almasou** [comment]
Actually this fix this issue. Thank you.

May I close this issue or better wait for the instructions to be updated.

Thanks for your great work.

**Comment by benzea** [comment]
Yes, the issue should remain open until the instructions are updated.
