### ISSUE TITLE
Language selection for questionnaire

### ISSUE THREAD

**Issue by benzea** [sdaps/sdaps_web#7]
It should be possible to select the LaTeX (bable) language for the questionnaire.

There are various things to keep in mind. In general, SDAPS has translations for the questionnaire. These are only used for the information and the "draft" overlay though.

We have two translation systems here in principle:
 * gettext (not currently build, but easy to add to sdaps core)
 * LaTeX "dict" files (which do not hap to system/gettext languages)

My guess is a good approach is to go through gettext and install the translations we have to get a mapping from system language to LaTeX language that needs to be set. But, there may be better ways, in particular if we want to support setting languages for which we don't have any translations.

**Comment by TheRadialActive** [comment]
Fixed with 10982537971ac69e48f3ed650c262177db765e44
